In [18]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

data=pd.read_csv("../input/Iris.csv")

from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

data=data.drop(['Id'],axis=1)

x=data.drop(['Species'],axis=1)
y=data['Species']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=4)
model=GaussianNB()
model.fit(x_train,y_train)
predicted=model.predict(x_test)
print(metrics.accuracy_score(y_test,predicted))
print(metrics.classification_report(y_test,predicted))
print(metrics.confusion_matrix(y_test,predicted))
new_data=[[3,4,5,6],[7,8,9,10],[1,3.4,5.6,7.8],[3,4,5,2],[5,4,2,2],[3, 2, 4, 0.2], [  4.7, 3, 1.3, 0.2 ]]
print(model.predict(new_data))





0.9777777777777777
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        21
Iris-versicolor       0.91      1.00      0.95        10
 Iris-virginica       1.00      0.93      0.96        14

       accuracy                           0.98        45
      macro avg       0.97      0.98      0.97        45
   weighted avg       0.98      0.98      0.98        45

[[21  0  0]
 [ 0 10  0]
 [ 0  1 13]]
['Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa']
